language: node_js

node_js:
  - node

services:
  - mysql
 
before_install:
  - cd ./merApi

install:
  - npm install


before_script:
  - mysql -e "create database mer"
  - mysql -uroot -e "grant all privileges on mer.* to 'user'@'%' identified by '123qwe'"
  - npx sequelize-cli db:seed:all  
  
script:
  - npm test

after_success: npm run coverage

# notifications:
#  slack: projectosipt20182019:rARE6PX1hJuNVzPBseXumyHG