language: node_js

node_js:
  - node

services:
  - mysql
 
before_install:
  - mysql -e "create database mer"
  - cd ./merApi

install:
  - npm install
  - npx sequelize-cli db:seed:all
  
script:
  - npm test


# notifications:
#  slack: projectosipt20182019:rARE6PX1hJuNVzPBseXumyHG